[package]
name = "gobject_subclassing_1"
version = "0.1.0"
authors = ["Julian Hofer <julianhofer@gnome.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
package = "gtk4"
path = "../../../gtk4"