[book]
authors = ["Julian Hofer"]
language = "en"
multilingual = false
src = "src"
title = "GUI development with Rust and GTK 4"


[output.html]
git-repository-url = "https://gitlab.gnome.org/Hofer-Julian/gtk-rs-book"
git-repository-icon = "fa-gitlab"
